// Generated by gencpp from file grobot_utilities/PatrolFeedback.msg
// DO NOT EDIT!


#ifndef GROBOT_UTILITIES_MESSAGE_PATROLFEEDBACK_H
#define GROBOT_UTILITIES_MESSAGE_PATROLFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grobot_utilities
{
template <class ContainerAllocator>
struct PatrolFeedback_
{
  typedef PatrolFeedback_<ContainerAllocator> Type;

  PatrolFeedback_()
    : completed_patrols(0)  {
    }
  PatrolFeedback_(const ContainerAllocator& _alloc)
    : completed_patrols(0)  {
  (void)_alloc;
    }



   typedef uint32_t _completed_patrols_type;
  _completed_patrols_type completed_patrols;





  typedef boost::shared_ptr< ::grobot_utilities::PatrolFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grobot_utilities::PatrolFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct PatrolFeedback_

typedef ::grobot_utilities::PatrolFeedback_<std::allocator<void> > PatrolFeedback;

typedef boost::shared_ptr< ::grobot_utilities::PatrolFeedback > PatrolFeedbackPtr;
typedef boost::shared_ptr< ::grobot_utilities::PatrolFeedback const> PatrolFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grobot_utilities::PatrolFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grobot_utilities::PatrolFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grobot_utilities::PatrolFeedback_<ContainerAllocator1> & lhs, const ::grobot_utilities::PatrolFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.completed_patrols == rhs.completed_patrols;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grobot_utilities::PatrolFeedback_<ContainerAllocator1> & lhs, const ::grobot_utilities::PatrolFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grobot_utilities

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::grobot_utilities::PatrolFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grobot_utilities::PatrolFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grobot_utilities::PatrolFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grobot_utilities::PatrolFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grobot_utilities::PatrolFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grobot_utilities::PatrolFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grobot_utilities::PatrolFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "226aac64e0bd3a8c3f4dd6f9847da700";
  }

  static const char* value(const ::grobot_utilities::PatrolFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x226aac64e0bd3a8cULL;
  static const uint64_t static_value2 = 0x3f4dd6f9847da700ULL;
};

template<class ContainerAllocator>
struct DataType< ::grobot_utilities::PatrolFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grobot_utilities/PatrolFeedback";
  }

  static const char* value(const ::grobot_utilities::PatrolFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grobot_utilities::PatrolFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"uint32 completed_patrols\n"
"\n"
;
  }

  static const char* value(const ::grobot_utilities::PatrolFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grobot_utilities::PatrolFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.completed_patrols);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PatrolFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grobot_utilities::PatrolFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grobot_utilities::PatrolFeedback_<ContainerAllocator>& v)
  {
    s << indent << "completed_patrols: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.completed_patrols);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROBOT_UTILITIES_MESSAGE_PATROLFEEDBACK_H
