// Generated by gencpp from file grobot_utilities/PatrolResult.msg
// DO NOT EDIT!


#ifndef GROBOT_UTILITIES_MESSAGE_PATROLRESULT_H
#define GROBOT_UTILITIES_MESSAGE_PATROLRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grobot_utilities
{
template <class ContainerAllocator>
struct PatrolResult_
{
  typedef PatrolResult_<ContainerAllocator> Type;

  PatrolResult_()
    : success(false)  {
    }
  PatrolResult_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::grobot_utilities::PatrolResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grobot_utilities::PatrolResult_<ContainerAllocator> const> ConstPtr;

}; // struct PatrolResult_

typedef ::grobot_utilities::PatrolResult_<std::allocator<void> > PatrolResult;

typedef boost::shared_ptr< ::grobot_utilities::PatrolResult > PatrolResultPtr;
typedef boost::shared_ptr< ::grobot_utilities::PatrolResult const> PatrolResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grobot_utilities::PatrolResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grobot_utilities::PatrolResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grobot_utilities::PatrolResult_<ContainerAllocator1> & lhs, const ::grobot_utilities::PatrolResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grobot_utilities::PatrolResult_<ContainerAllocator1> & lhs, const ::grobot_utilities::PatrolResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grobot_utilities

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::grobot_utilities::PatrolResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grobot_utilities::PatrolResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grobot_utilities::PatrolResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grobot_utilities::PatrolResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grobot_utilities::PatrolResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grobot_utilities::PatrolResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grobot_utilities::PatrolResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::grobot_utilities::PatrolResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::grobot_utilities::PatrolResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grobot_utilities/PatrolResult";
  }

  static const char* value(const ::grobot_utilities::PatrolResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grobot_utilities::PatrolResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"bool success\n"
;
  }

  static const char* value(const ::grobot_utilities::PatrolResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grobot_utilities::PatrolResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PatrolResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grobot_utilities::PatrolResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grobot_utilities::PatrolResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROBOT_UTILITIES_MESSAGE_PATROLRESULT_H
