# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from grobot_utilities/PatrolGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PatrolGoal(genpy.Message):
  _md5sum = "923e7ebd662f0085a303d0235a0a1450"
  _type = "grobot_utilities/PatrolGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
float32 radius
bool clockwise
uint32 num_patrols
"""
  __slots__ = ['radius','clockwise','num_patrols']
  _slot_types = ['float32','bool','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       radius,clockwise,num_patrols

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PatrolGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.radius is None:
        self.radius = 0.
      if self.clockwise is None:
        self.clockwise = False
      if self.num_patrols is None:
        self.num_patrols = 0
    else:
      self.radius = 0.
      self.clockwise = False
      self.num_patrols = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_fBI().pack(_x.radius, _x.clockwise, _x.num_patrols))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.radius, _x.clockwise, _x.num_patrols,) = _get_struct_fBI().unpack(str[start:end])
      self.clockwise = bool(self.clockwise)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_fBI().pack(_x.radius, _x.clockwise, _x.num_patrols))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.radius, _x.clockwise, _x.num_patrols,) = _get_struct_fBI().unpack(str[start:end])
      self.clockwise = bool(self.clockwise)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_fBI = None
def _get_struct_fBI():
    global _struct_fBI
    if _struct_fBI is None:
        _struct_fBI = struct.Struct("<fBI")
    return _struct_fBI
