(cl:defpackage grobot_utilities-msg
  (:use )
  (:export
   "<PATROLACTION>"
   "PATROLACTION"
   "<PATROLACTIONFEEDBACK>"
   "PATROLACTIONFEEDBACK"
   "<PATROLACTIONGOAL>"
   "PATROLACTIONGOAL"
   "<PATROLACTIONRESULT>"
   "PATROLACTIONRESULT"
   "<PATROLFEEDBACK>"
   "PATROLFEEDBACK"
   "<PATROLGOAL>"
   "PATROLGOAL"
   "<PATROLRESULT>"
   "PATROLRESULT"
  ))

