; Auto-generated. Do not edit!


(cl:in-package grobot_utilities-msg)


;//! \htmlinclude PatrolResult.msg.html

(cl:defclass <PatrolResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass PatrolResult (<PatrolResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PatrolResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PatrolResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name grobot_utilities-msg:<PatrolResult> is deprecated: use grobot_utilities-msg:PatrolResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <PatrolResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader grobot_utilities-msg:success-val is deprecated.  Use grobot_utilities-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PatrolResult>) ostream)
  "Serializes a message object of type '<PatrolResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PatrolResult>) istream)
  "Deserializes a message object of type '<PatrolResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PatrolResult>)))
  "Returns string type for a message object of type '<PatrolResult>"
  "grobot_utilities/PatrolResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PatrolResult)))
  "Returns string type for a message object of type 'PatrolResult"
  "grobot_utilities/PatrolResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PatrolResult>)))
  "Returns md5sum for a message object of type '<PatrolResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PatrolResult)))
  "Returns md5sum for a message object of type 'PatrolResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PatrolResult>)))
  "Returns full string definition for message of type '<PatrolResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PatrolResult)))
  "Returns full string definition for message of type 'PatrolResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PatrolResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PatrolResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PatrolResult
    (cl:cons ':success (success msg))
))
