; Auto-generated. Do not edit!


(cl:in-package grobot_utilities-msg)


;//! \htmlinclude PatrolGoal.msg.html

(cl:defclass <PatrolGoal> (roslisp-msg-protocol:ros-message)
  ((radius
    :reader radius
    :initarg :radius
    :type cl:float
    :initform 0.0)
   (clockwise
    :reader clockwise
    :initarg :clockwise
    :type cl:boolean
    :initform cl:nil)
   (num_patrols
    :reader num_patrols
    :initarg :num_patrols
    :type cl:integer
    :initform 0))
)

(cl:defclass PatrolGoal (<PatrolGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PatrolGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PatrolGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name grobot_utilities-msg:<PatrolGoal> is deprecated: use grobot_utilities-msg:PatrolGoal instead.")))

(cl:ensure-generic-function 'radius-val :lambda-list '(m))
(cl:defmethod radius-val ((m <PatrolGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader grobot_utilities-msg:radius-val is deprecated.  Use grobot_utilities-msg:radius instead.")
  (radius m))

(cl:ensure-generic-function 'clockwise-val :lambda-list '(m))
(cl:defmethod clockwise-val ((m <PatrolGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader grobot_utilities-msg:clockwise-val is deprecated.  Use grobot_utilities-msg:clockwise instead.")
  (clockwise m))

(cl:ensure-generic-function 'num_patrols-val :lambda-list '(m))
(cl:defmethod num_patrols-val ((m <PatrolGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader grobot_utilities-msg:num_patrols-val is deprecated.  Use grobot_utilities-msg:num_patrols instead.")
  (num_patrols m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PatrolGoal>) ostream)
  "Serializes a message object of type '<PatrolGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'radius))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'clockwise) 1 0)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'num_patrols)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'num_patrols)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'num_patrols)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'num_patrols)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PatrolGoal>) istream)
  "Deserializes a message object of type '<PatrolGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'radius) (roslisp-utils:decode-single-float-bits bits)))
    (cl:setf (cl:slot-value msg 'clockwise) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'num_patrols)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'num_patrols)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'num_patrols)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'num_patrols)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PatrolGoal>)))
  "Returns string type for a message object of type '<PatrolGoal>"
  "grobot_utilities/PatrolGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PatrolGoal)))
  "Returns string type for a message object of type 'PatrolGoal"
  "grobot_utilities/PatrolGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PatrolGoal>)))
  "Returns md5sum for a message object of type '<PatrolGoal>"
  "923e7ebd662f0085a303d0235a0a1450")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PatrolGoal)))
  "Returns md5sum for a message object of type 'PatrolGoal"
  "923e7ebd662f0085a303d0235a0a1450")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PatrolGoal>)))
  "Returns full string definition for message of type '<PatrolGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 radius~%bool clockwise~%uint32 num_patrols~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PatrolGoal)))
  "Returns full string definition for message of type 'PatrolGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 radius~%bool clockwise~%uint32 num_patrols~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PatrolGoal>))
  (cl:+ 0
     4
     1
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PatrolGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PatrolGoal
    (cl:cons ':radius (radius msg))
    (cl:cons ':clockwise (clockwise msg))
    (cl:cons ':num_patrols (num_patrols msg))
))
